{
 "title": "Logs / Unifi / Overview",
 "tags": [
  "Unifi",
  "Loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "unifi-exporter" },
   {
    "name": "smooth",
    "label": "Smooth",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "type",
    "label": "Type",
    "query": {}
   },
   {
    "name": "service_name",
    "label": "Service",
    "query": {}
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {}
   },
   {
    "name": "facility",
    "label": "Facility",
    "query": {}
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Global (No Filters)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Volume",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Critical Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", level=\"critical\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", level=\"error\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", level=\"warning\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", level=\"informational\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Notice Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", level=\"notice\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Debug Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"$job\", level=\"debug\"} [$__auto]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Logs By Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(type) (count_over_time({job=\"$job\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Logs By Level",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({job=\"$job\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Logs By Facility",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(facility) (count_over_time({job=\"$job\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Logs By Hostname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(hostname) (count_over_time({job=\"$job\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  { "title": "Filtered", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Log Volume By Level",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({job=\"$job\", service_name=~\"$service_name\", level=~\"$severity\", hostname=~\"$hostname\", facility=~\"$facility\", type=~\"$type\"} [$__auto]))",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Log Volume By Service",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name) (count_over_time({job=\"$job\", service_name=~\"$service_name\", level=~\"$severity\", hostname=~\"$hostname\", facility=~\"$facility\", type=~\"$type\"} [$__auto]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Log Volume By Hostname",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(hostname) (count_over_time({job=\"$job\", service_name=~\"$service|$service_name\", level=~\"$severity\", hostname=~\"$hostname\", facility=~\"$facility\", type=~\"$type\"} [$__auto]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Last 100 Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\", service_name=~\"$service_name\", level=~\"$severity\", hostname=~\"$hostname\", facility=~\"$facility\", type=~\"$type\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}